// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CARE_ArimotoPotter_cpp
arma::mat CARE_ArimotoPotter_cpp(const arma::mat& A, const arma::mat& B, const arma::mat& Q, const arma::mat& R);
RcppExport SEXP _AREsolver_CARE_ArimotoPotter_cpp(SEXP ASEXP, SEXP BSEXP, SEXP QSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(CARE_ArimotoPotter_cpp(A, B, Q, R));
    return rcpp_result_gen;
END_RCPP
}
// DARE_ArimotoPotter_cpp
arma::mat DARE_ArimotoPotter_cpp(const arma::mat& A, const arma::mat& B, const arma::mat& Q, const arma::mat& R);
RcppExport SEXP _AREsolver_DARE_ArimotoPotter_cpp(SEXP ASEXP, SEXP BSEXP, SEXP QSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(DARE_ArimotoPotter_cpp(A, B, Q, R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AREsolver_CARE_ArimotoPotter_cpp", (DL_FUNC) &_AREsolver_CARE_ArimotoPotter_cpp, 4},
    {"_AREsolver_DARE_ArimotoPotter_cpp", (DL_FUNC) &_AREsolver_DARE_ArimotoPotter_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AREsolver(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
