# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CARE_ArimotoPotter_cpp <- function(A, B, Q, R) {
    .Call(`_AREsolver_CARE_ArimotoPotter_cpp`, A, B, Q, R)
}

DARE_ArimotoPotter_cpp <- function(A, B, Q, R) {
    .Call(`_AREsolver_DARE_ArimotoPotter_cpp`, A, B, Q, R)
}

